version: '3.8'

services:
  postgres-db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB=pagnet
      POSTGRES_USER=user
      POSTGRES_PASSWORD=123456

  spring-app:
    image: backend-pagnet:latest
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-db:5432/pagnet
    depends_on:
      - postgres-db

  # SPA Application
  spa-app:
    build:
      context: ./frontend # Path to your SPA project directory
      dockerfile: Dockerfile # Specify the Dockerfile to use
    ports:
      - "9090:9090" # Map host port to container port
    depends_on:
      - spring-app